{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "4dc96408_39b7432f",
        "filename": "src/test/java/com/googlesource/gerrit/plugins/multisite/validation/BatchRefUpdateValidatorTest.java",
        "patchSetId": 2
      },
      "lineNbr": 153,
      "author": {
        "id": 1083454
      },
      "writtenOn": "2021-04-13T21:33:46Z",
      "side": 1,
      "message": "this test is failing because here it should be false. It\u0027s already fixed on stable-3.3. It was passing before just by coincidence. But with the ref rollback we change the the logic and the issue occurs. I can push the fix but than someone else have to give +2",
      "range": {
        "startLine": 153,
        "startChar": 57,
        "endLine": 153,
        "endChar": 61
      },
      "revId": "45d99b51b3066dfb5861d4a7f09829b185370275",
      "serverId": "173816e5-2b9a-37c3-8a2e-48639d4f1153"
    }
  ]
}